#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : pipewire
Version  : 0.2.7
Release  : 11
URL      : file:///insilications/build/clearlinux/packages/pipewire/pipewire-0.2.7.tar.gz
Source0  : file:///insilications/build/clearlinux/packages/pipewire/pipewire-0.2.7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1+
Requires: pipewire-bin = %{version}-%{release}
Requires: pipewire-lib = %{version}-%{release}
Requires: pipewire-services = %{version}-%{release}
BuildRequires : SDL2-dev
BuildRequires : SDL2-staticdev
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader-dev
BuildRequires : buildreq-meson
BuildRequires : dbus-dev
BuildRequires : glib-dev
BuildRequires : glib-staticdev
BuildRequires : gst-plugins-base-dev
BuildRequires : gstreamer-dev
BuildRequires : libsndfile-dev
BuildRequires : libsndfile-staticdev
BuildRequires : libva-dev
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(bluez)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-plugins-base-1.0)
BuildRequires : pkgconfig(jack)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(sbc)
BuildRequires : pkgconfig(sndfile)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(vulkan)
BuildRequires : pkgconfig(x11)
BuildRequires : sbc-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
# Ignore missing build ids
%undefine _missing_build_ids_terminate_build
# Disable automatic requeriments processing
AutoReq: no

%description
PipeWire
--------
PipeWire is a server and user space API to deal with multimedia
pipelines. This includes:

%package bin
Summary: bin components for the pipewire package.
Group: Binaries
Requires: pipewire-services = %{version}-%{release}

%description bin
bin components for the pipewire package.


%package dev
Summary: dev components for the pipewire package.
Group: Development
Requires: pipewire-lib = %{version}-%{release}
Requires: pipewire-bin = %{version}-%{release}
Provides: pipewire-devel = %{version}-%{release}
Requires: pipewire = %{version}-%{release}

%description dev
dev components for the pipewire package.


%package lib
Summary: lib components for the pipewire package.
Group: Libraries

%description lib
lib components for the pipewire package.


%package services
Summary: services components for the pipewire package.
Group: Systemd services

%description services
services components for the pipewire package.


%prep
%setup -q -n pipewire
cd %{_builddir}/pipewire

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600587890
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -DPIC -ffat-lto-objects -fPIC"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden -flto-partition=none
# gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common -fno-plt -fno-semantic-interposition
export CXXFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -DPIC -ffat-lto-objects -fPIC"
#
export FCFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -DPIC -ffat-lto-objects -fPIC"
export FFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -DPIC -ffat-lto-objects -fPIC"
export CFFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -DPIC -ffat-lto-objects -fPIC"
#
export LDFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -DPIC -ffat-lto-objects -fPIC"
#
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%define _lto_cflags 1
#%define _lto_cflags %{nil}
#
# export PATH="/usr/lib64/ccache/bin:$PATH"
# export CCACHE_NOHASHDIR=1
# export CCACHE_DIRECT=1
# export CCACHE_SLOPPINESS=pch_defines,locale,time_macros
# export CCACHE_DISABLE=1
## altflags1 end
##
%define _lto_cflags 1
##
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dvulkan=true -Ddefault_library=shared  builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pipewire
/usr/bin/pipewire-cli
/usr/bin/pipewire-monitor
/usr/bin/spa-inspect
/usr/bin/spa-monitor

%files dev
%defattr(-,root,root,-)
/usr/include/pipewire/array.h
/usr/include/pipewire/client.h
/usr/include/pipewire/command.h
/usr/include/pipewire/control.h
/usr/include/pipewire/core.h
/usr/include/pipewire/data-loop.h
/usr/include/pipewire/extensions/client-node.h
/usr/include/pipewire/extensions/protocol-native.h
/usr/include/pipewire/factory.h
/usr/include/pipewire/global.h
/usr/include/pipewire/interfaces.h
/usr/include/pipewire/introspect.h
/usr/include/pipewire/link.h
/usr/include/pipewire/log.h
/usr/include/pipewire/loop.h
/usr/include/pipewire/main-loop.h
/usr/include/pipewire/map.h
/usr/include/pipewire/mem.h
/usr/include/pipewire/module.h
/usr/include/pipewire/node.h
/usr/include/pipewire/pipewire.h
/usr/include/pipewire/port.h
/usr/include/pipewire/properties.h
/usr/include/pipewire/protocol.h
/usr/include/pipewire/proxy.h
/usr/include/pipewire/remote.h
/usr/include/pipewire/resource.h
/usr/include/pipewire/stream.h
/usr/include/pipewire/thread-loop.h
/usr/include/pipewire/type.h
/usr/include/pipewire/utils.h
/usr/include/pipewire/version.h
/usr/include/pipewire/work-queue.h
/usr/include/spa/buffer/buffer.h
/usr/include/spa/buffer/meta.h
/usr/include/spa/clock/clock.h
/usr/include/spa/graph/graph.h
/usr/include/spa/monitor/monitor.h
/usr/include/spa/node/command.h
/usr/include/spa/node/event.h
/usr/include/spa/node/io.h
/usr/include/spa/node/node.h
/usr/include/spa/param/audio/format-utils.h
/usr/include/spa/param/audio/format.h
/usr/include/spa/param/audio/raw-utils.h
/usr/include/spa/param/audio/raw.h
/usr/include/spa/param/buffers.h
/usr/include/spa/param/format-utils.h
/usr/include/spa/param/format.h
/usr/include/spa/param/io.h
/usr/include/spa/param/meta.h
/usr/include/spa/param/param.h
/usr/include/spa/param/props.h
/usr/include/spa/param/video/chroma.h
/usr/include/spa/param/video/color.h
/usr/include/spa/param/video/encoded.h
/usr/include/spa/param/video/format-utils.h
/usr/include/spa/param/video/format.h
/usr/include/spa/param/video/multiview.h
/usr/include/spa/param/video/raw-utils.h
/usr/include/spa/param/video/raw.h
/usr/include/spa/pod/builder.h
/usr/include/spa/pod/command.h
/usr/include/spa/pod/event.h
/usr/include/spa/pod/iter.h
/usr/include/spa/pod/parser.h
/usr/include/spa/pod/pod.h
/usr/include/spa/support/log-impl.h
/usr/include/spa/support/log.h
/usr/include/spa/support/loop.h
/usr/include/spa/support/plugin.h
/usr/include/spa/support/type-map-impl.h
/usr/include/spa/support/type-map.h
/usr/include/spa/utils/defs.h
/usr/include/spa/utils/dict.h
/usr/include/spa/utils/hook.h
/usr/include/spa/utils/list.h
/usr/include/spa/utils/ringbuffer.h
/usr/include/spa/utils/type.h
/usr/lib64/libpipewire-0.2.so
/usr/lib64/pkgconfig/libpipewire-0.2.pc
/usr/lib64/pkgconfig/libspa-0.1.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/gstreamer-1.0/libgstpipewire.so
/usr/lib64/libpipewire-0.2.so.1
/usr/lib64/libpipewire-0.2.so.1.207.0
/usr/lib64/pipewire-0.2/libpipewire-module-audio-dsp.so
/usr/lib64/pipewire-0.2/libpipewire-module-autolink.so
/usr/lib64/pipewire-0.2/libpipewire-module-client-node.so
/usr/lib64/pipewire-0.2/libpipewire-module-link-factory.so
/usr/lib64/pipewire-0.2/libpipewire-module-mixer.so
/usr/lib64/pipewire-0.2/libpipewire-module-portal.so
/usr/lib64/pipewire-0.2/libpipewire-module-protocol-native.so
/usr/lib64/pipewire-0.2/libpipewire-module-rtkit.so
/usr/lib64/pipewire-0.2/libpipewire-module-spa-monitor.so
/usr/lib64/pipewire-0.2/libpipewire-module-spa-node-factory.so
/usr/lib64/pipewire-0.2/libpipewire-module-spa-node.so
/usr/lib64/pipewire-0.2/libpipewire-module-suspend-on-idle.so
/usr/lib64/spa/alsa/libspa-alsa.so
/usr/lib64/spa/audiomixer/libspa-audiomixer.so
/usr/lib64/spa/audiotestsrc/libspa-audiotestsrc.so
/usr/lib64/spa/bluez5/libspa-bluez5.so
/usr/lib64/spa/support/libspa-dbus.so
/usr/lib64/spa/support/libspa-support.so
/usr/lib64/spa/test/libspa-test.so
/usr/lib64/spa/v4l2/libspa-v4l2.so
/usr/lib64/spa/videotestsrc/libspa-videotestsrc.so
/usr/lib64/spa/volume/libspa-volume.so

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/pipewire.service
/usr/lib/systemd/user/pipewire.socket
